# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
   
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y software-properties-common \
             gnupg2 wget ca-certificates apt-transport-https
	   
        #Install docker 
        groupadd -g 998 docker
        sudo -E curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu       $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get -y install docker-ce docker-ce-cli containerd.io
        sudo adduser vagrant docker 

 
	    #Install Powershell
        wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
		sudo apt-get update
		sudo apt-get install -y powershell
		sudo rm -f packages-microsoft-prod.deb
	SHELL
	config.trigger.after :up do |trigger|
         #trigger.info = "Starting bootstrap.ps1 #{ENV['target']} #{ENV['verbosity']}"
		 trigger.info = "Starting bootstrap.ps1 -Target Default -Verbosity Diagnostic"
        trigger.run_remote = {:inline=>"cd /vagrant && pwsh bootstrap.ps1 -Target Default -Verbosity Diagnostic"}
    end
end